import { CommonType, DefaultValueType, KeyValueType, trans } from './transtypes';

const common: CommonType = {
  main_subtit: 'Short but powerful',
  main_introduce: 'Sign in to continue.',
  login: 'Sign in',
  signin: 'Sign in',
  sign_in_required: 'Sign In Required',
  confirm: 'Confirm',
  reset_password: 'Reset password',
  resend_code: 'Re-send',
  verify_code_page: 'Retrieve password',
  enter_verify_code: 'Enter the verification code',
  forgot_password: 'Password recovery',
  recover_your_account:
    'Enter your email address below and we will send you a link to reset your password',
  change_password: 'New password',
  change_password_your_account: 'Enter a new password',
  re_password_input: 'Confirm your new password',
  signin_to_your_account: 'Sign into your account.',
  skip: 'Skip',
  email: 'Email Address',
  email_input: 'Email Address (example@gmail.com)',
  password_input: 'Password',
  password_verify: 'Verify password.',
  no_account: 'No account?',
  create_one: 'Create one!',
  skip_detail: 'Skip',
  episodes: 'Episodes',
  episodesTitle: 'Episodes',
  season: 'Season',
  all: 'ALL',
  allStreaming: 'ALL',
  allCapital: 'All',
  all2: 'ALL',
  description: 'Description',
  vote: 'Vote',
  cast: 'Cast',
  storyline: 'Storyline',
  detail: 'Detail',
  details: 'Details',
  crew: 'Crew',
  director: 'Director',
  writer: 'Writer',
  like: 'Like',
  bookmark: 'Bookmarks',
  save: 'Save',
  saved: 'Saved',
  share: 'Share',
  streaming: 'STREAMING',
  crowdfunding: 'CROWDFUNDING',
  events: 'NOTICES & EVENTS',
  apply: 'APPLY',
  blog: 'BLOG',
  store: 'STORE',
  home: 'HOME',
  login_is_required: 'Please sign in to continue',
  do_you_want_login: '',
  participants: 'Participants',
  vote2: 'Vote',
  writeAComment: 'Write a comment...',
  comment: 'Comment',
  refresh: 'Refresh',
  popular: 'Popular',
  latest: 'Latest',
  round: 'Round',
  my_page: 'MY PAGE',
  sign_out: 'Sign out',
  sign_out_question1: 'Are you sure you want to log out?',
  sign_out_question2: 'There is still a lot of content you have not seen.',
  sign_up: 'Sign up',
  userEmail: 'Email',
  apply_title: 'Got a brilliant idea?',
  apply_title2: 'We will help you bring it to life.',
  apply_sub: 'Show your talent to the world and find sponsors who will love what you create.',
  apply_sub2: 'Get support from Terafty.',
  personal_company_name: 'Personal/Company name',
  personal_company_name_plh: 'Please enter the Individual/team/company name.',
  mobile_number: 'Mobile Number',
  project_plh: 'Please enter the title.',
  project_details_plh: 'Please write the project details.',
  estimated_cost: 'Estimated cost',
  estimated_cost_plh: 'How much do you want to raise?',
  production_schedule: 'Production Schedule',
  production_schedule_plh: 'Give us a rough estimate.',
  additional_information: 'Additional Information',
  additional_information_plh: 'Tells us a bit more about it.',
  popular_search_keyword: 'Popular search keyword',
  create_a_new_account: 'Please enter the email and password you want to use.',
  accept_the_terms_of_use: 'Accept the terms of use (required)',
  privacy_policy: 'Privacy Policy (required)',
  next: 'Next',
  search: 'Search',
  birth_date: 'Date of Birth',
  basic_information: 'Tell us about yourself',
  enjoy_a_variety_of_videos: 'Enjoy a variety of videos.',
  name: 'Name',
  nationality: 'Nationality',
  registration_complete: 'Registration complete',
  modifications_completed: 'Complete',
  to_do_next: 'Next',
  edit_profile: 'Edit Profile',
  email_authentication: 'Email Authentication',
  please_enter_your_email: 'Please enter your email.',
  enter_the_verification_code: 'Enter the verification code.',
  survey: 'How did you hear about us?',
  gender: 'Gender',
  notice: 'Notice',
  proceeding: 'Ongoing',
  cancel: 'Cancel',
  end: 'Ended',
  lookup: 'Views',
  listView: 'See more',
  basic_information2: 'Basic Information',
  surveySub1: 'How did you come to use the service?',
  surveySub2: 'We will try to improve our service.',
  webDrama: 'Web Series',
  shortMovies: 'Short Movies',
  shortMovie: 'Short Movie',
  musicVideos: 'Music Videos',
  musicVideo: 'Music Video',
  recent: 'Recent',
  select: 'Select',
  byGenre: 'By Genre',
  voted: 'Voted',
  editProfile: 'Edit Profile',
  finished: 'Finished',
  ongoing: 'Ongoing',
  myVote: 'My Vote',
  likedList: 'Liked',
  bookmarkList: 'Bookmarks',
  loading: 'Loading ...',
  cancelLiked: 'Liked',
  application_complete: 'Application Complete',
  application_sub_1: 'Successfully applied',
  application_sub_2: 'Please wait for your reply.',
  play: 'Play',
  firstComment: 'Be the first to comment!',
  haveNoData: 'Have no data!',
  haveNoVote: 'No Ongoing Poll.',
  noInformation: 'No information',
  period: 'Period',
  newPassword: 'New Password',
  loginSuccess: 'Login Success!',
  backers: 'backers',
  updatedAt: 'Last updated',
  agree: 'Agree',
  text_and_number_only: "Must be Number, Korea or English.",
};

const defaultKeyValue: DefaultValueType = {
  facebook: 'Facebook',
  instargram: 'Instargram',
  google: 'Google',
  otherInletChannel: 'Other. Please specify (optional)',
  choose_your_gender: 'Choose your gender',
  male: 'Male',
  female: 'Female',
  unchecked: 'Unchecked',
  private: 'Private',
};

const errorMessage = {
  er_login: 'Please check your email or password',
  newPassword:
    'Password must be Minimum 8 and maximum 15 characters, at least one uppercase letter, one lowercase letter, one number and one special character',
  userPassword:
    'Password must be Minimum 8 and maximum 15 characters, at least one uppercase letter, one lowercase letter, one number and one special character',
  userPassword_confirmation: 'Please check your password',
  er_email_to_retrieve_code:
    'Please check your email again, maybe your email does not exist in system',
  er_change_password: 'Please check your password or re enter password form again',
  er_enter_code: 'Please check code in your email again',
  please_choose: 'Please select at least one product!',
  voting_failed: 'Voting failed!',
  comment_failed: 'Comment failed!',
  password_required: 'Password is a required field',
  validate_required: '{{value}} is a required field',
  validate_input_not_valid: 'The input is not valid {{value}}',
  validate_field_mlte: 'This field length must be more than {min} or equal to {max} characters.',
  validate_password: 'Please check your ID or password',
  validate_password_not_match: 'Password not match',
  validate_min: '{{value}} must be at least {{min}} characters',
  unauthentication: 'Your authentication fail. Please authenticate again',
};

const keyValue: KeyValueType = {
  user_id: 'User Id',
  userPassword: 'Password',
  confirmPassword: 'Confirm password',
  name: 'Name',
  userEmail: 'Email',
  email: 'Email',
  email_tax: 'Email',
  certificationNumber: 'Certification number',
  phone: 'Phone number',
  address: 'address',
  codeOTP: 'codeOTP',
  title: 'Project',
  content: 'Project Detail',
  userName: 'Name',
  newPassword: 'New password',
};

const applyPage = {
  apply_company_name: 'What is your name?',
  apply_project_name: 'What is the project title?',
  apply_type_video: 'What type of video do you want to produce?',
  apply_type_video_1: 'Short Movies',
  apply_type_video_2: 'Web Series',
  apply_type_video_3: 'Music Videos',
  apply_project_content: 'What is your project about?',
  apply_email: 'What is your email address?',
  apply_phone: 'What is your mobile number?',
  apply_budget: 'What is your funding goal?',
  apply_how_long: 'How long would your project take?',
  apply_link: 'Please share your portfolio link.',
  apply_expect_benefit: 'What benefit are you most interested in?',
  apply_expect_benefit_1: 'Support English subtitle',
  apply_expect_benefit_2: 'Provide customized information for target overseas markets',
  apply_expect_benefit_3: 'Provide marketing location',
  apply_expect_benefit_4: 'Partial support for production costs when selecting an excellent team',
  apply_extra_information: 'Please enter additional information (if any)',
};

const transEN: trans = {
  common,
  defaultKeyValue,
  errorMessage,
  keyValue,
  applyPage,
};

export default transEN;
