import { CommonType, DefaultValueType, KeyValueType, trans } from './transtypes';

const common: CommonType = {
  main_subtit: '짧지만 잔상이 오래가는 작품',
  main_introduce: '로그인하고 더 많은 서비스를 이용하세요.',
  login: '로그인',
  signin: '로그인하기',
  sign_in_required: '로그인',
  signin_to_your_account: '이메일과 비밀번호를 입력해주세요.',
  skip: '둘러보기',
  email: '이메일 주소',
  email_input: '이메일 주소 (example@gmail.com)',
  password_input: '비밀번호',
  password_verify: '비밀번호 확인',
  confirm: '확인',
  reset_password: '변경하기',
  resend_code: '재전송',
  verify_code_page: '비밀번호 찾기',
  enter_verify_code: '인증번호를 입력하세요',
  forgot_password: '비밀번호 찾기',
  recover_your_account: '등록된 이메일을 입력하십시오.',
  change_password: '비밀번호 변경',
  change_password_your_account: '새로운 비밀번호로 변경하세요.',
  re_password_input: '비밀번호 확인',
  no_account: '아이디가 없나요?',
  create_one: '회원가입하세요.',
  skip_detail: '둘러보기',
  episodes: '회차',
  episodesTitle: '회차',
  season: '시즌',
  all: '전체관람',
  allStreaming: '전체',
  allCapital: '전체',
  all2: '전체보기',
  description: '상세설명',
  vote: '투표',
  cast: '등장인물',
  storyline: '줄거리',
  detail: '제작정보',
  details: '제작정보',
  crew: '제작진',
  director: '감독',
  writer: '극본',
  like: '좋아요',
  bookmark: '북마크',
  newPassword: '새 비밀번호',
  save: '저장하기',
  saved: 'Saved',
  share: '공유하기',
  streaming: '스트리밍',
  crowdfunding: '크라우드 펀딩',
  events: '공지 & 이벤트',
  apply: '지원하기',
  blog: '블로그',
  store: '스토어',
  home: '홈',
  login_is_required: '로그인이 필요합니다.',
  do_you_want_login: '로그인 하시겠습니까?',

  participants: '명 참여',
  vote2: '투표하기',
  writeAComment: '댓글을 입력해주세요...',
  comment: '등록',
  refresh: '새로고침',
  popular: '인기순',
  latest: '최신순',
  round: '회차',
  my_page: '마이페이지',
  sign_out: '로그아웃',
  sign_out_question1: '로그아웃하시겠어요?',
  sign_out_question2: '못 보신 컨텐츠가 아직 많아요.',
  sign_up: '회원가입',
  userEmail: '이메일',
  apply_title: '당신의 영감, 상상을 보내 주세요.',
  apply_title2: '실현할 수 있도록 도와드리겠습니다.',
  apply_sub: '테라프티와 함께 세계로 뻗어나갈 영상크리에이터를 모십니다.',
  apply_sub2: '테라프티에서 서포트를 받으세요.',
  personal_company_name: '개인/회사 이름',
  personal_company_name_plh: '(주)가나다라마',
  mobile_number: '전화번호',
  project_plh: '프로젝트 제목을 적어 주세요.',
  project_details_plh: '프로젝트 내용을 작성해 주세요.',
  estimated_cost: '필요 예산',
  estimated_cost_plh: 'ex.1000만원, 미정 등',
  production_schedule: '프로젝트 집행 일정',
  production_schedule_plh: 'ex.한달, 2주 등',
  additional_information: '추가 내용',
  additional_information_plh: '내용을 작성해 주세요.',
  popular_search_keyword: '인기 검색어',
  create_a_new_account: '사용할 이메일과 비밀번호를 입력해주세요.',
  accept_the_terms_of_use: '이용약관 동의 (필수)',
  privacy_policy: '개인정보 처리 방침 (필수)',
  next: '다음',
  search: '검색',
  birth_date: '생년월일',
  basic_information: '기본정보',
  enjoy_a_variety_of_videos: '다양한 영상을 즐겨 보세요.',
  name: '이름',
  nationality: '국적',
  registration_complete: '가입완료',
  modifications_completed: '수정완료',
  to_do_next: '다음에 하기',
  edit_profile: '내 정보 수정',
  email_authentication: '이메일 인증',
  please_enter_your_email: '이메일을 입력하세요.',
  enter_the_verification_code: '인증번호를 입력하세요.',
  survey: '유입 채널',
  gender: '성별',
  notice: '공지사항',
  proceeding: '진행중',
  cancel: '취소',
  end: '종료',
  lookup: '조회',
  listView: '목록보기',
  basic_information2: '기본 정보',
  surveySub1: '어떤 경로로 서비스를 이용하게 됐나요?',
  surveySub2: '서비스 향상에 노력하겟습니다.',
  webDrama: '웹 시리즈',
  shortMovies: '단편 영화',
  shortMovie: '단편 영화',
  musicVideos: '뮤직비디오',
  musicVideo: '뮤직비디오',
  recent: '최신순',
  select: '선택',
  byGenre: '장르별',
  voted: '투표 현황',
  editProfile: '내 정보 수정',
  finished: '종료',
  ongoing: '진행중',
  myVote: '내 투표',
  likedList: '좋아요 목록',
  bookmarkList: '북마크 목록',
  loading: '로딩 ...',
  cancelLiked: '좋아요 취소',
  application_complete: '지원 완료',
  application_sub_1: '성공적으로 지원 됐습니다.',
  application_sub_2: '확인 후 연락 드리겠습니다.',
  play: '재생',
  firstComment: '첫 댓글을 남겨보세요!',
  haveNoData: '데이터가 존재하지 않습니다.',
  haveNoVote: '진행 중인 투표가 없습니다.',
  noInformation: '정보 없음',
  period: '기간',
  loginSuccess: '로그인 성공!',
  backers: '후원자',
  updatedAt: '마지막 업데이트',
  agree: '동의',
  text_and_number_only: "숫자, 한글 또는 영문이어야 합니다.."
};

const defaultKeyValue: DefaultValueType = {
  facebook: '페이스북',
  instargram: '인스타그램',
  google: '구글',
  otherInletChannel: '기타',
  choose_your_gender: '성별 선택',
  male: '남자',
  female: '여자',
  unchecked: '선택 안함',
  private: '비공개',
};

const errorMessage = {
  er_login: '이메일 또는 비밀번호를 확인하세요.',
  newPassword:
    '비밀번호는 최소 8자~최대 15자, 대문자 1개 이상, 소문자 1개, 숫자 1개, 특수문자 1개 이상이어야 합니다.',
  userPassword:
    '비밀번호는 최소 8자~최대 15자, 대문자 1개 이상, 소문자 1개, 숫자 1개, 특수문자 1개 이상이어야 합니다.',
  userPassword_confirmation: '비밀번호를 확인해 주세요',
  er_email_to_retrieve_code: 'Please check your email again',
  er_change_password: '비밀번호형식을 다시 확인하세요',
  er_enter_code: 'Please check your code in email again',
  please_choose: '하나 이상의 제품을 선택하십시오!',
  voting_failed: '투표 실패!',
  comment_failed: '댓글 실패!',
  password_required: '비밀번호를 입력하세요.',

  validate_required: '{{value}}를 입력하세요.',
  validate_input_not_valid: '입력이 유효하지 않습니다 {{value}}',
  validate_field_mlte: '이 필드 길이는 {{min}}보다 크거나 {{max}}자 이상이어야 합니다.',
  validate_password: '아이디 또는 비밀번호를 확인해 주세요',
  validate_password_not_match: '비밀번호 일치하지 않습니다 ',
  validate_email: '{{value}}은 이메일 형식이어야 합니다.',
  validate_min: '{{value}}는 최소 {{min}}자 이상 입력해야 합니다.',
  unauthentication: '인증에 실패했습니다. 다시 인증해주세요',
};

const keyValue: KeyValueType = {
  user_id: '아이디',
  userPassword: '비밀번호',
  confirmPassword: '비밀번호 확인',
  name: '이름',
  userEmail: '이메일',
  email: '이메일',
  email_tax: '이메일',
  certificationNumber: '인증 번호',
  phone: '휴대폰 번호',
  additional_contact: '추가 연락처',
  address: '주소',
  codeOTP: 'codeOTP',
  title: '프로젝트',
  content: '프로젝트 세부 정보',
  userName: '이름',
  newPassword: '새 비밀번호',
};

const applyPage = {
  apply_company_name: '지원하시는 개인/팀/회사 이름을 알려주세요.',
  apply_project_name: '프로젝트 이름을 알려주세요.',
  apply_type_video: '만들고자 하시는 영상의 유형을 알려주세요.',
  apply_type_video_1: '단편영화',
  apply_type_video_2: '웹드라마',
  apply_type_video_3: '뮤직비디오',
  apply_project_content: '프로젝트 내용을 간단히 소개해주세요.',
  apply_email: '연락드릴 이메일을 알려주세요.',
  apply_phone: '연락드릴 휴대폰 번호를 알려주세요.',
  apply_budget: '목표 펀딩 금액을 알려주세요.',
  apply_how_long: '프로젝트를 완료 하는 데 어느 정도의 시간이 소요될까요?',
  apply_link: '포트폴리오 링크를 첨부해주세요.',
  apply_expect_benefit: '관심가는 혜택을 알려주세요 (복수 선택 가능).',
  apply_expect_benefit_1: '영어 통번역 지원',
  apply_expect_benefit_2: '타겟 해외 시장 맞춤 정보 제공',
  apply_expect_benefit_3: '펀딩 캠페인 홍보 지원',
  apply_expect_benefit_4: '우수팀 선정시 제작비 일부 지원',
  apply_extra_information: '추가 정보가 있을 시 알려주세요.',
};

const transKR: trans = {
  common,
  defaultKeyValue,
  errorMessage,
  keyValue,
  applyPage,
};

export default transKR;
